const Map<String, String> en = {
  /// Common
  'welcome': 'Welcome',
  'change_language': 'Change Language',

  /// SignUp
  'create_account': 'Create Your Account',
  'greeting_user': 'Hello, @name',
  'enter_mobile': 'Enter your mobile number to get started.',
  'username': 'User Name',
  'hint_name': 'John Smith',
  'mobile_number': 'Mobile Number',
  'get_code': 'Get the code',
  'already_account': 'Already have an account? ',
  'login': 'Login',
  'fill_fields': 'Please fill in all fields',

  /// Home
  //'book_heavy_vehicles': 'Book Heavy Vehicles Instantly',
  'book_heavy_vehicles': 'Book Any Heavy Vehicle in Seconds — Cars to JCBs!',

  ///OTP SCREEN
  'confirm_number': 'Confirm Your Number',
  'enter_code_sent': 'Enter the code we sent ',
  'edit_mobile': 'Edit mobile number',
  'dont_get_sms': "Don't get an SMS? ",
  'send_again': 'Send again',
  'login_btn': 'Login',

  ///LOGIN SCREEN
  'welcome_back': 'Welcome Back',
  'login_subtitle':
      'Login with your mobile number to continue booking heavy vehicles.',
  'enter_registered_mobile': 'Enter your registered mobile number',
  'no_account': "Don't have an account? ",
  'create_account_link': 'Create Account',
  'enter_mobile_error': 'Please enter your mobile number',
  'enter_register_number': 'Enter the registered number',

  ///HOME SCREEN
  'hello': 'Hello, ',
  'next_destination': 'Whers your next destination?',
  'search': 'Search...',
  'choose_vehicle': 'Choose Vehicle',
  'see_all': 'See All',
  'top_trends': 'Top Trends',
  'most_booked': 'Most booked vehicles.',
  'all': 'All',
  'car': 'Car',
  'jcb': 'JCB',
  'lorry': 'Lorry',
  'capacity': 'Capacity',
  'fare': 'Fare',
  'eta': 'ETA',
  'book_now': 'Book now',
  'book_n': 'Book now',
  'home': 'Home',
  'my_booking': 'My Booking',
  'profile': 'Profile',
  'container_truck': 'Container Truck',
  'tons': 'Tons',
  'per_km': '₹25/km',
  'mins': 'mins',
  'most_booked_prefix': 'Most booked ',
  'sedan_car': 'Sedan Car',
  'jcb_machine': 'JCB Machine',
  'mini_lorry': 'Mini Lorry',
  'truck': 'Truck',
  'tataace': 'Tata Ace',
  'bus': 'Bus',
  'tractor': 'Tractor',
  'agri': 'Agriculture',
  'mini_bus': 'Mini Bus',
  'ac_bus': 'AC Bus',
  'farm_tractor': 'Farm Tractor',
  'harvest_machine': 'Harvest Machine',
  'tata_ace': 'Tata Ace',
  //----Vehicle Card widget
  'passengers': 'Passengers',
  'hour': 'Hour',
  'day': 'Day',
  '_km': '/ km',

  ///VEHICLE DETAILS SCREEN
  'back': 'Back',
  'heavy_duty': 'Heavy Duty',
  'available_247': '24/7 Available',
  'trips_completed': 'trips completed',
  'distance': 'Distance',
  'vehicle_specifications': 'Vehicle Specifications',
  'payload': 'Payload',
  'cargo_box': 'Cargo Box',
  'axle_type': 'Axle Type',
  'fuel_type': 'Fuel Type',
  'loading_type': 'Loading Type',
  'suitable_for': 'Suitable For',
  'multi_axle': 'Multi Axle',
  'diesel': 'Diesel',
  'rear_loading': 'Rear Loading',
  'heavy_goods': 'Heavy Goods',
  'km': 'km',
  'ton': 'Ton',

  ///Booking Screen
  'booking_id': 'Booking ID',
  'trip_details': 'Trip Details',
  'pickup': 'PICKUP',
  'drop': 'Drop',
  'date': 'Date',
  'time': 'Time',
  'payment': 'Payment',
  'total': 'Total',
  'call_driver': 'Call Driver',

  // Profile
  'member_since': 'Member since',
  'edit_profile': 'Edit Profile',
  'payment_methods': 'Payment Methods',
  'notification_settings': 'Notification Settings',
  'saved_addresses': 'Saved Addresses',
  'vehicle_preferences': 'Vehicle Preferences',
  'lorry_trucks': 'Lorry / Trucks',
  'jcb_excavators': 'JCB / Excavators',
  'car_tatacce': 'Car / Tata Ace',
  'log_out': 'Log Out',
  'logout_confirm': 'Are you sure you want to log out?',
  'cancel': 'Cancel',
  'confirm': 'Confirm',

  ///Vehicle booking details screen
  'booking_details': 'Booking Details',
  'pickup_address': 'Pickup Address',
  'drop_address': 'Drop Address',
  'schedule_booking': 'Schedule Booking',
  'schedule_later': 'Schedule Later',
  'driver_details': 'Driver Details',
  'rating': 'Rating',
  'verified_driver': 'Verified Driver',
  'years_experience': 'Years Experience',
  'km_based': 'KM Based',
  'hour_based': 'Hour Based',
  'additional_services': 'Additional Services',
  'add_loading_helper': 'Add Loading Helper',
  'add_unloading_helper': 'Add Unloading Helper',
  'insurance_coverage': 'Insurance Coverage',
  'return_trip_required': 'Return Trip Required',
  'discuss': 'Discuss',
  'special_instructions': 'Special Instructions',
  'instructions_hint': 'Add any loading instructions (optional)',
  'instructions_example': 'Example: Need crane support for unloading.',
  'estimated_fare': 'Estimated Fare',
  'base_fare': 'Base Fare',
  'platform_fee': 'Platform Fee',
  'gst': 'GST (5%)',
  'total_estimate': 'Total Estimate',
  'fare_note': 'Final fare may vary based on actual distance and time.',
  'apply_promo_code': 'Apply Promo Code',
  'enter_promo_hint': 'Enter promo code',
  'apply': 'Apply',
  'promo_error': 'Error',
  'enter_promo': 'Please enter a promo code',
  'promo_invalid': 'Invalid Code',
  'promo_invalid_msg': 'This promo code is not valid.',
  'payment_method': 'Payment Method',
  'safety_assurance': 'Safety Assurance',
  'support_24_7': '24/7 Support',
  'confirm_booking': 'Confirm Booking',
  //-----Booking Confirm dialog
  'booking_confirmed': 'Booking Confirmed!',
  'vehicle_on_way': 'Your vehicle is on the way',
  'booking_id_label': 'Booking ID: ',
  'view_booking': 'View Booking',

  ///---------WIDGETS -------
  //APP SNACK BAR
  'success': 'Success',
  'error': 'Error',
  'warning': 'Warning',
  'login_success': 'Login successful',
  'login_failed': 'Invalid credentials',
};
