const Map<String, String> ta = {
  'welcome': 'வரவேற்கிறோம்',
  'change_language': 'மொழி மாற்று',

  'create_account': 'உங்கள் கணக்கை உருவாக்கவும்',
  'enter_mobile': 'தொடங்க உங்கள் மொபைல் எண்ணை உள்ளிடவும்.',
  'username': 'பயனர் பெயர்',
  'hint_name': 'ஜான் ஸ்மித்',
  'mobile_number': 'மொபைல் எண்',
  'get_code': 'குறியீட்டை பெறவும்',
  'already_account': 'ஏற்கனவே கணக்கு உள்ளதா? ',
  'login': 'உள்நுழை',
  'fill_fields': 'அனைத்து புலங்களையும் நிரப்பவும்',

  'book_heavy_vehicles': 'கனரக வாகனங்களை உடனே முன்பதிவு செய்யுங்கள்',

  /// OTP SCREEN
  'confirm_number': 'உங்கள் எண்ணை உறுதிப்படுத்தவும்',
  'enter_code_sent': 'நாங்கள் அனுப்பிய குறியீட்டை உள்ளிடவும் ',
  'edit_mobile': 'மொபைல் எண்ணை திருத்தவும்',
  'dont_get_sms': 'SMS வரவில்லையா? ',
  'send_again': 'மீண்டும் அனுப்பு',
  'login_btn': 'உள்நுழை',

  ///LOGIN SCREEN
  'welcome_back': 'மீண்டும் வரவேற்கிறோம்',
  'login_subtitle':
      'கனரக வாகனங்களை முன்பதிவு செய்ய உங்கள் மொபைல் எண்ணை உள்ளிடவும்.',
  'enter_registered_mobile': 'பதிவு செய்யப்பட்ட மொபைல் எண்ணை உள்ளிடவும்',
  'no_account': 'கணக்கு இல்லையா? ',
  'create_account_link': 'கணக்கு உருவாக்கவும்',
  'enter_mobile_error': 'உங்கள் மொபைல் எண்ணை உள்ளிடவும்',
  'enter_register_number': 'பதிவு செய்யப்பட்ட எண்ணை உள்ளிடவும்',

  ///HOME SCREEN
  'hello': 'வணக்கம், ',
  'next_destination': 'உங்கள் அடுத்த இலக்கு எங்கே?',
  'search': 'தேடு...',
  'choose_vehicle': 'வாகனம் தேர்ந்தெடுக்கவும்',
  'see_all': 'அனைத்தும் காண்க',
  'top_trends': 'சிறந்த போக்குகள்',
  'most_booked': 'அதிகம் முன்பதிவு செய்யப்பட்ட வாகனங்கள்.',
  'all': 'அனைத்தும்',
  'car': 'கார்',
  'jcb': 'ஜேசிபி',
  'lorry': 'லாரி',
  'capacity': 'கொள்ளளவு',
  'fare': 'கட்டணம்',
  'eta': 'வருகை நேரம்',
  'book_now': 'இப்போது முன்பதிவு',
  'home': 'முகப்பு',
  'my_booking': 'என் முன்பதிவு',
  'profile': 'சுயவிவரம்',
  'container_truck': 'கன்டெய்னர் டிரக்',
  'tons': 'டன்',
  'per_km': '₹25/கி.மீ',
  'mins': 'நிமிடங்கள்',
  'most_booked_prefix': 'அதிகம் முன்பதிவான ',
  'sedan_car': 'செடான் கார்',
  'jcb_machine': 'ஜேசிபி இயந்திரம்',
  'mini_lorry': 'மினி லாரி',
  'truck': 'டிரக்',

  ///VEHICLE DETAILS SCREEN
  'back': 'திரும்பு',
  'heavy_duty': 'கனரக பணி',
  'available_247': '24/7 கிடைக்கும்',
  'trips_completed': 'பயணங்கள் முடிந்தன',
  'distance': 'தூரம்',
  'vehicle_specifications': 'வாகன விவரக்குறிப்புகள்',
  'payload': 'சுமை எடை',
  'cargo_box': 'சரக்கு பெட்டி',
  'axle_type': 'அச்சு வகை',
  'fuel_type': 'எரிபொருள் வகை',
  'loading_type': 'ஏற்றுதல் வகை',
  'suitable_for': 'பொருத்தமானது',
  'multi_axle': 'பல அச்சு',
  'diesel': 'டீசல்',
  'rear_loading': 'பின் ஏற்றுதல்',
  'heavy_goods': 'கனரக சரக்கு',
  'km': 'கி.மீ',
  'ton': 'டன்',

  ///Booking Screen
  'booking_id': 'முன்பதிவு எண்',
  'trip_details': 'பயண விவரங்கள்',
  'pickup': 'எடுக்கும் இடம்',
  'drop': 'இறங்கும் இடம்',
  'date': 'தேதி',
  'time': 'நேரம்',
  'payment': 'பணம்',
  'total': 'மொத்தம்',
  'call_driver': 'ஓட்டுனரை அழைக்கவும்',

  ///---------WIDGETS -------
  //APP SNACK BAR
  'success': 'வெற்றி',
  'error': 'பிழை',
  'warning': 'எச்சரிக்கை',
  'login_success': 'உள்நுழைவு வெற்றிகரமாக முடிந்தது',
  'login_failed': 'தவறான தகவல்கள்',
};
