const Map<String, String> ta = {
  'welcome': 'வரவேற்கிறோம்',
  'change_language': 'மொழி மாற்று',

  'create_account': 'உங்கள் கணக்கை உருவாக்கவும்',
  'greeting_user': 'வணக்கம், @name',
  'enter_mobile': 'தொடங்க உங்கள் மொபைல் எண்ணை உள்ளிடவும்.',
  'username': 'பயனர் பெயர்',
  'hint_name': 'ஜான் ஸ்மித்',
  'mobile_number': 'மொபைல் எண்',
  'get_code': 'குறியீட்டை பெறவும்',
  'already_account': 'ஏற்கனவே கணக்கு உள்ளதா? ',
  'login': 'உள்நுழை',
  'fill_fields': 'அனைத்து புலங்களையும் நிரப்பவும்',

  'book_heavy_vehicles': 'கார் முதல் JCB வரை — ஒரே App-ல் உடனே முன்பதிவு',
  // 'book_heavy_vehicles': 'கனரக வாகனங்களை உடனே முன்பதிவு செய்யுங்கள்',

  /// OTP SCREEN
  'confirm_number': 'உங்கள் எண்ணை உறுதிப்படுத்தவும்',
  'enter_code_sent': 'நாங்கள் அனுப்பிய குறியீட்டை உள்ளிடவும் ',
  'edit_mobile': 'மொபைல் எண்ணை திருத்தவும்',
  'dont_get_sms': 'SMS வரவில்லையா? ',
  'send_again': 'மீண்டும் அனுப்பு',
  'login_btn': 'உள்நுழை',

  ///LOGIN SCREEN
  'welcome_back': 'மீண்டும் வரவேற்கிறோம்',
  'login_subtitle':
      'கனரக வாகனங்களை முன்பதிவு செய்ய உங்கள் மொபைல் எண்ணை உள்ளிடவும்.',
  'enter_registered_mobile': 'பதிவு செய்யப்பட்ட மொபைல் எண்ணை உள்ளிடவும்',
  'no_account': 'கணக்கு இல்லையா? ',
  'create_account_link': 'கணக்கு உருவாக்கவும்',
  'enter_mobile_error': 'உங்கள் மொபைல் எண்ணை உள்ளிடவும்',
  'enter_register_number': 'பதிவு செய்யப்பட்ட எண்ணை உள்ளிடவும்',

  ///HOME SCREEN
  'hello': 'வணக்கம், ',
  'next_destination': 'உங்கள் அடுத்த இலக்கு எங்கே?',
  'search': 'தேடு...',
  'choose_vehicle': 'வாகனம் தேர்ந்தெடுக்கவும்',
  'see_all': 'அனைத்தும் காண்க',
  'top_trends': 'சிறந்த போக்குகள்',
  'most_booked': 'அதிகம் முன்பதிவு செய்யப்பட்ட வாகனங்கள்.',
  'all': 'அனைத்தும்',
  'car': 'கார்',
  'jcb': 'ஜேசிபி',
  'lorry': 'லாரி',
  'capacity': 'கொள்ளளவு',
  'fare': 'கட்டணம்',
  'eta': 'வருகை நேரம்',
  'book_now': 'இப்போது முன்பதிவு',
  'book_n': 'முன்பதிவு',
  'home': 'முகப்பு',
  'my_booking': 'என் முன்பதிவு',
  'profile': 'சுயவிவரம்',
  'container_truck': 'கன்டெய்னர் டிரக்',
  'tons': 'டன்',
  'per_km': '₹25/கி.மீ',
  'mins': 'நிமிடங்கள்',
  'most_booked_prefix': 'அதிகம் முன்பதிவான ',
  'sedan_car': 'செடான் கார்',
  'jcb_machine': 'ஜேசிபி இயந்திரம்',
  'mini_lorry': 'மினி லாரி',
  'truck': 'டிரக்',
  'tataace': 'டாடா ஏஸ்',
  'bus': 'பஸ்',
  'tractor': 'டிராக்டர்',
  'agri': 'விவசாயம்',
  'mini_bus': 'மினி பஸ்',
  'ac_bus': 'ஏசி பஸ்',
  'farm_tractor': 'பண்ணை டிராக்டர்',
  'harvest_machine': 'அறுவடை இயந்திரம்',
  'tata_ace': 'டாடா ஏஸ்',
  //---Vehicle card----
  'passengers': 'பயணிகள்',
  'hour': 'மணி',
  'day': 'நாள்',
  '_km': '/ கிமீ',

  ///VEHICLE DETAILS SCREEN
  'back': 'திரும்பு',
  'heavy_duty': 'கனரக பணி',
  'available_247': '24/7 கிடைக்கும்',
  'trips_completed': 'பயணங்கள் முடிந்தன',
  'distance': 'தூரம்',
  'vehicle_specifications': 'வாகன விவரக்குறிப்புகள்',
  'payload': 'சுமை எடை',
  'cargo_box': 'சரக்கு பெட்டி',
  'axle_type': 'அச்சு வகை',
  'fuel_type': 'எரிபொருள் வகை',
  'loading_type': 'ஏற்றுதல் வகை',
  'suitable_for': 'பொருத்தமானது',
  'multi_axle': 'பல அச்சு',
  'diesel': 'டீசல்',
  'rear_loading': 'பின் ஏற்றுதல்',
  'heavy_goods': 'கனரக சரக்கு',
  'km': 'கி.மீ',
  'ton': 'டன்',

  ///Booking Screen
  'booking_id': 'முன்பதிவு எண்',
  'trip_details': 'பயண விவரங்கள்',
  'pickup': 'எடுக்கும் இடம்',
  'drop': 'இறங்கும் இடம்',
  'date': 'தேதி',
  'time': 'நேரம்',
  'payment': 'பணம்',
  'total': 'மொத்தம்',
  'call_driver': 'ஓட்டுனரை அழைக்கவும்',

  // Profile
  'member_since': 'உறுப்பினர் தொடங்கி',
  'edit_profile': 'சுயவிவரத்தை திருத்து',
  'payment_methods': 'கட்டண முறைகள்',
  'notification_settings': 'அறிவிப்பு அமைப்புகள்',
  'saved_addresses': 'சேமித்த முகவரிகள்',
  'vehicle_preferences': 'வாகன விருப்பத்தேர்வுகள்',
  'lorry_trucks': 'லாரி / டிரக்குகள்',
  'jcb_excavators': 'ஜேசிபி / எக்ஸ்கேவேட்டர்கள்',
  'car_tatacce': 'கார் / டாடா ஏஸ்',
  'log_out': 'வெளியேறு',
  'logout_confirm': 'நீங்கள் வெளியேற விரும்புகிறீர்களா?',
  'cancel': 'ரத்து செய்',
  'confirm': 'உறுதிப்படுத்து',

  ///Vehicle booking details screen
  'booking_details': 'பதிவு விவரங்கள்',
  'pickup_address': 'எடுக்கும் முகவரி',
  'drop_address': 'இறக்கும் முகவரி',
  'schedule_booking': 'பதிவு திட்டமிடு',
  'schedule_later': 'பிறகு திட்டமிடு',
  'driver_details': 'டிரைவர் விவரங்கள்',
  'rating': 'மதிப்பீடு',
  'verified_driver': 'சரிபார்க்கப்பட்ட டிரைவர்',
  'years_experience': 'ஆண்டு அனுபவம்',
  'km_based': 'கி.மீ அடிப்படை',
  'hour_based': 'மணி அடிப்படை',
  'additional_services': 'கூடுதல் சேவைகள்',
  'add_loading_helper': 'ஏற்றும் உதவியாளர்',
  'add_unloading_helper': 'இறக்கும் உதவியாளர்',
  'insurance_coverage': 'காப்பீட்டு பாதுகாப்பு',
  'return_trip_required': 'திரும்பும் பயணம் தேவை',
  'discuss': 'விவாதிக்கவும்',
  'special_instructions': 'சிறப்பு வழிமுறைகள்',
  'instructions_hint': 'ஏற்றுவதற்கான வழிமுறைகளை சேர்க்கவும் (விரும்பினால்)',
  'instructions_example': 'உதாரணம்: இறக்குவதற்கு கிரேன் தேவை.',
  'estimated_fare': 'மதிப்பிடப்பட்ட கட்டணம்',
  'base_fare': 'அடிப்படை கட்டணம்',
  'platform_fee': 'தளக் கட்டணம்',
  'gst': 'ஜிஎஸ்டி (5%)',
  'total_estimate': 'மொத்த மதிப்பீடு',
  'fare_note': 'இறுதி கட்டணம் தூரம் மற்றும் நேரத்தின் அடிப்படையில் மாறலாம்.',
  'apply_promo_code': 'விளம்பர குறியீட்டை பயன்படுத்து',
  'enter_promo_hint': 'விளம்பர குறியீட்டை உள்ளிடவும்',
  'apply': 'பயன்படுத்து',
  'promo_error': 'பிழை',
  'enter_promo': 'விளம்பர குறியீட்டை உள்ளிடவும்',
  'promo_invalid': 'தவறான குறியீடு',
  'promo_invalid_msg': 'இந்த விளம்பர குறியீடு செல்லாது.',
  'payment_method': 'கட்டண முறை',
  'safety_assurance': 'பாதுகாப்பு உத்தரவாதம்',
  'support_24_7': '24/7 ஆதரவு',
  'confirm_booking': 'பதிவை உறுதிப்படுத்து',

  //-----Booking Confirm dialog
  'booking_confirmed': 'பதிவு உறுதிப்படுத்தப்பட்டது!',
  'vehicle_on_way': 'உங்கள் வாகனம் வழியில் உள்ளது',
  'booking_id_label': 'பதிவு எண்: ',
  'view_booking': 'பதிவை காண்க',

  ///---------WIDGETS -------
  //APP SNACK BAR
  'success': 'வெற்றி',
  'error': 'பிழை',
  'warning': 'எச்சரிக்கை',
  'login_success': 'உள்நுழைவு வெற்றிகரமாக முடிந்தது',
  'login_failed': 'தவறான தகவல்கள்',
};
